#SPDX-License-Identifier: MIT-0
---
- name: Task-1 Install required packages
  ansible.builtin.dnf:
    name: 
     - httpd
     - firewalld
    state: present
- name: Task-2 Copying index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'
    setype: httpd_sys_content_t
- name: Task-3 Starting Services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - httpd
    - firewalld
- name: Task-4 Allowing Http over firewall
  ansible.posix.firewalld:
    state: enabled
    permanent: true
    service: http
    immediate: true
