---
- name: Q11 - Playbook to handle lvm
  hosts: dev
  gather_facts: true
  become: true
  vars:
    vg_name: research
    lv_name: data
    lv_size: 300
    lv_alt_size: 200
  tasks:
    - name: Check if "{{ vg_name }}" present 
      ansible.builtin.fail:
        msg: "{{ vg_name }} volume group does not exists"
      when: ansible_facts['lvm']['vgs'][vg_name] is not defined
    - name: Handling Logical Volume
      block:
        - name: Creating Logical Volume of "{{ lv_size }}"
          community.general.lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ lv_size }}"
            state: present 
          register: lv_block
      rescue:
        - name: Error Message
          ansible.builtin.debug:
            msg: "Could not create logical volume of {{ lv_size }} size"

        - name: Creating Logical Volume of "{{ lv_alt_size }}"
          community.general.lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ lv_alt_size }}"
            state: present 
          register: lv_rescue
      always:
        - name: Creating File system
          ansible.builtin.filesystem:
            dev: "/dev/{{ vg_name }}/{{ lv_name }}"
            fstype: ext4
            force: true
          when: ( lv_block is defined and lv_block is changed) or ( lv_rescue is defined and lv_rescue is changed )
