---
- name: Q15 - Creating users
  hosts: dev,balancer
  gather_facts: true
  become: true
  vars_files:
    - locker.yml
    - user_list.yml
  tasks:
    - name: Play-1 Creating supplimentary groups
      ansible.builtin.group:
        name: "{{ item.groupname }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ mygroups }}"
    - name: Play-2 Creating developer users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        state: present
        shell: /bin/bash
        password: "{{ PW_developer | password_hash('sha512') }}"
        groups: devops
        append: yes
      when: 
        - item.type == "developer"
        - inventory_hostname in groups['dev']
      loop: "{{ myusers }}"

    - name: Play-2 Creating manager users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        state: present
        shell: /bin/bash
        password: "{{ PW_manager | password_hash('sha512') }}"
        groups: opsmgr
        append: yes
      when: 
        - item.type == "manager"
        - inventory_hostname in groups['balancer']
      loop: "{{ myusers }}"

