---
- name: Q3 - Playbook1 to install packages php,mariadb
  hosts: dev
  gather_facts: true
  become: true
  tasks:
    - name: Install php-mariadb on dev servers
      ansible.builtin.dnf:
        name: [php,mariadb]
        state: present

- name: Q3 - Playbook2 to install rpm dev tool
  hosts: dev
  gather_facts: true
  become: true
  tasks:
    - name: Install php-mariadb on dev servers
      ansible.builtin.dnf:
        name: "@RPM Development Tools"
        state: present

    - name: Upgrading all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

