---
- name: Q4 - Configure timesync using system-role
  hosts: all
  gather_facts: true
  become: true
  vars:
    timesync_ntp_provider: ""
    timesync_ntp_servers:
      - hostname: 10.10.1.200
        ibursh: true
  tasks:
    - name: Configuring timesync
      ansible.builtin.import_role:
        name: rhel-system-roles.timesync 
