---
- name: Q9 - Playbook to use custom role
  hosts: webservers
  gather_facts: true
  become: true
  tasks:
    - name: Importing Apache role
      ansible.builtin.import_role:
        name: apache

